export const NODE_DEPS = {
  react: "React",
  next: "Next.js",
  "@angular/core": "Angular",
  vue: "Vue.js",
  svelte: "Svelte",
  jquery: "jQuery",
  express: "Express",
  "express-async-errors": "Express",
  "express-session": "Express",
  "@nestjs/core": "NestJS",
  koa: "Koa",
  fastify: "Fastify",
  redux: "Redux",
  zustand: "Zustand",
  mobx: "MobX",
  "@reduxjs/toolkit": "Redux Toolkit",
  tailwindcss: "Tailwind CSS",
  sass: "Sass",
  less: "Less",
  "styled-components": "Styled Components",
  "@emotion/react": "Emotion",
  "@emotion/styled": "Emotion",
  webpack: "Webpack",
  vite: "Vite",
  parcel: "Parcel",
  rollup: "Rollup",
  "@babel/core": "Babel",
  jest: "Jest",
  mocha: "Mocha",
  chai: "Chai",
  cypress: "Cypress",
  "@testing-library/react": "React Testing Library",
  "@testing-library/jest-dom": "React Testing Library",
  mongoose: "Mongoose",
  mongodb: "MongoDB",
  prisma: "Prisma",
  sequelize: "Sequelize",
  typeorm: "TypeORM",
  knex: "Knex.js",
  pg: "PostgreSQL",
  mysql: "MySQL",
  mysql2: "MySQL",
  redis: "Redis",
  "@supabase/supabase-js": "Supabase",
  lodash: "Lodash",
  moment: "Moment.js",
  dayjs: "Day.js",
  axios: "Axios",
  "node-fetch": "Fetch API",
  eslint: "ESLint",
  prettier: "Prettier",
  graphql: "GraphQL",
  "apollo-server": "Apollo Server",
  "apollo-server-express": "Apollo Server",
  "apollo-client": "Apollo Client",
  "@apollo/client": "Apollo Client",
  "socket.io": "Socket.IO",
  "socket.io-client": "Socket.IO",
  ws: "WebSocket",
  passport: "Passport.js",
  jsonwebtoken: "JWT",
  typescript: "TypeScript",
  dotenv: "dotenv",
  nodemon: "Nodemon",
  pm2: "PM2",
};

export const PYTHON_DEPS = {
  django: "Django",
  flask: "Flask",
  fastapi: "FastAPI",
  starlette: "Starlette",
  aiohttp: "aiohttp",
  numpy: "NumPy",
  pandas: "Pandas",
  scipy: "SciPy",
  "scikit-learn": "Scikit-learn",
  tensorflow: "TensorFlow",
  keras: "Keras",
  torch: "PyTorch",
  matplotlib: "Matplotlib",
  seaborn: "Seaborn",
  sqlalchemy: "SQLAlchemy",
  psycopg2: "PostgreSQL (psycopg2)",
  "psycopg2-binary": "PostgreSQL (psycopg2)",
  "mysql-connector-python": "MySQL Connector",
  pymongo: "PyMongo",
  redis: "Redis",
  celery: "Celery",
  requests: "Requests",
  httpx: "HTTPX",
  beautifulsoup4: "Beautiful Soup",
  scrapy: "Scrapy",
  pytest: "Pytest",
  unittest: "Unittest",
  pydantic: "Pydantic",
  "python-dotenv": "dotenv",
};

export const JAVA_DEPS = {
  spring: "Spring",
  "spring-boot": "Spring Boot",
  hibernate: "Hibernate",
  jpa: "Java Persistence API (JPA)",
  junit: "JUnit",
  log4j: "Log4j",
  slf4j: "SLF4J",
  apache: "Apache Commons",
  guava: "Guava",
  okhttp: "OkHttp",
  retrofit: "Retrofit",
  gson: "Gson",
  jackson: "Jackson",
  apachepoi: "Apache POI",
  jsoup: "Jsoup",
  jaxb: "JAXB",
};

export const DOTNET_DEPS = {
  "Microsoft.AspNetCore.Mvc": "ASP.NET Core MVC",
  "Microsoft.EntityFrameworkCore": "Entity Framework Core",
  "Microsoft.AspNetCore.Identity": "ASP.NET Core Identity",
  "Microsoft.Extensions.Logging": "Logging",
  "Newtonsoft.Json": "Json.NET",
  AutoMapper: "AutoMapper",
  MediatR: "MediatR",
  FluentValidation: "FluentValidation",
  Serilog: "Serilog",
  NLog: "NLog",
  Dapper: "Dapper",
  Hangfire: "Hangfire",
  Quartz: "Quartz.NET",
};

export const RUBY_DEPS = {
  rails: "Ruby on Rails",
  sinatra: "Sinatra",
  rspec: "RSpec",
  capybara: "Capybara",
  active_record: "Active Record",
};

export const PHP_DEPS = {
  laravel: "Laravel",
  symfony: "Symfony",
  codeigniter: "CodeIgniter",
  yii: "Yii",
  phalcon: "Phalcon",
  slim: "Slim",
  zend: "Zend Framework",
  cakephp: "CakePHP",
  doctrine: "Doctrine ORM",
  monolog: "Monolog",
  guzzle: "Guzzle",
  phpunit: "PHPUnit",
  phpspec: "PHPSpec",
};

export const GO_DEPS = {
  gin: "Gin",
  echo: "Echo",
  gorilla: "Gorilla Mux",
  gorm: "GORM",
  sqlx: "SQLX",
  gofiber: "Fiber",
  gochi: "Gochi",
  revel: "Revel",
  buffalo: "Buffalo",
  testify: "Testify",
  logrus: "Logrus",
  zap: "Zap",
  viper: "Viper",
  cobra: "Cobra",
};

export const RUST_DEPS = {
  actix: "Actix",
  rocket: "Rocket",
  warp: "Warp",
  tokio: "Tokio",
  hyper: "Hyper",
  diesel: "Diesel",
  sqlx: "SQLX",
  serde: "Serde",
  clap: "Clap",
  log: "Log",
  reqwest: "Reqwest",
  rusqlite: "Rusqlite",
};

export const DART_DEPS = {
  flutter: "Flutter",
  dio: "Dio",
  http: "HTTP",
  provider: "Provider",
  riverpod: "Riverpod",
  bloc: "BLoC",
  sqflite: "Sqflite",
  shared_preferences: "Shared Preferences",
  json_serializable: "Json Serializable",
  get_it: "GetIt",
  freezed: "Freezed",
};

export const ELIXIR_DEPS = {
  phoenix: "Phoenix",
  ecto: "Ecto",
  plug: "Plug",
  absinthe: "Absinthe",
  poison: "Poison",
  jason: "Jason",
  ex_doc: "ExDoc",
  ex_unit: "ExUnit",
};

export const DOCKER_DEPS = {
  dockerfile: "Dockerfile",
  docker_compose: "Docker Compose",
  docker: "Docker CLI",
  docker_api: "Docker API",
  docker_sdk: "Docker SDK",
  docker_registry: "Docker Registry",
  docker_swarm: "Docker Swarm",
  kubernetes: "Kubernetes",
  openshift: "OpenShift",
};
