export const NODE_DEPS = {
  react: "React",
  next: "Next.js",
  "@angular/core": "Angular",
  vue: "Vue.js",
  svelte: "Svelte",
  jquery: "jQuery",
  express: "Express",
  "express-async-errors": "Express",
  "express-session": "Express",
  "@nestjs/core": "NestJS",
  koa: "Koa",
  fastify: "Fastify",
  redux: "Redux",
  zustand: "Zustand",
  mobx: "MobX",
  "@reduxjs/toolkit": "Redux Toolkit",
  tailwindcss: "Tailwind CSS",
  sass: "Sass",
  less: "Less",
  "styled-components": "Styled Components",
  "@emotion/react": "Emotion",
  "@emotion/styled": "Emotion",
  webpack: "Webpack",
  vite: "Vite",
  parcel: "Parcel",
  rollup: "Rollup",
  "@babel/core": "Babel",
  jest: "Jest",
  mocha: "Mocha",
  chai: "Chai",
  cypress: "Cypress",
  "@testing-library/react": "React Testing Library",
  "@testing-library/jest-dom": "React Testing Library",
  mongoose: "Mongoose",
  mongodb: "MongoDB",
  prisma: "Prisma",
  sequelize: "Sequelize",
  typeorm: "TypeORM",
  knex: "Knex.js",
  pg: "PostgreSQL",
  mysql: "MySQL",
  mysql2: "MySQL",
  redis: "Redis",
  "@supabase/supabase-js": "Supabase",
  lodash: "Lodash",
  moment: "Moment.js",
  dayjs: "Day.js",
  axios: "Axios",
  "node-fetch": "Fetch API",
  eslint: "ESLint",
  prettier: "Prettier",
  graphql: "GraphQL",
  "apollo-server": "Apollo Server",
  "apollo-server-express": "Apollo Server",
  "apollo-client": "Apollo Client",
  "@apollo/client": "Apollo Client",
  "socket.io": "Socket.IO",
  "socket.io-client": "Socket.IO",
  ws: "WebSocket",
  passport: "Passport.js",
  jsonwebtoken: "JWT",
  typescript: "TypeScript",
  dotenv: "dotenv",
  nodemon: "Nodemon",
  pm2: "PM2",
};

export const PYTHON_DEPS = {
  django: "Django",
  flask: "Flask",
  fastapi: "FastAPI",
  starlette: "Starlette",
  aiohttp: "aiohttp",
  numpy: "NumPy",
  pandas: "Pandas",
  scipy: "SciPy",
  "scikit-learn": "Scikit-learn",
  tensorflow: "TensorFlow",
  keras: "Keras",
  torch: "PyTorch",
  matplotlib: "Matplotlib",
  seaborn: "Seaborn",
  sqlalchemy: "SQLAlchemy",
  psycopg2: "PostgreSQL (psycopg2)",
  "psycopg2-binary": "PostgreSQL (psycopg2)",
  "mysql-connector-python": "MySQL Connector",
  pymongo: "PyMongo",
  redis: "Redis",
  celery: "Celery",
  requests: "Requests",
  httpx: "HTTPX",
  beautifulsoup4: "Beautiful Soup",
  scrapy: "Scrapy",
  pytest: "Pytest",
  unittest: "Unittest",
  pydantic: "Pydantic",
  "python-dotenv": "dotenv",
};

export const JAVA_DEPS = {
  "spring-boot-starter": "Spring Boot",
  "spring-boot-starter-web": "Spring Boot",
  "spring-core": "Spring Framework",
  "spring-web": "Spring Framework",
  "spring-webmvc": "Spring Framework",
  "spring-data-jpa": "Spring Data JPA",
  "spring-security-core": "Spring Security",
  "hibernate-core": "Hibernate",
  "jakarta.persistence-api": "Java Persistence API (JPA)",
  "javax.persistence-api": "Java Persistence API (JPA)",
  junit: "JUnit 4",
  "junit-jupiter-api": "JUnit 5",
  "junit-jupiter-engine": "JUnit 5",
  mockito: "Mockito",
  "mockito-core": "Mockito",
  "log4j-api": "Log4j 2",
  "log4j-core": "Log4j 2",
  "slf4j-api": "SLF4J",
  "logback-classic": "Logback",
  "logback-core": "Logback",
  "commons-lang3": "Apache Commons Lang",
  "commons-io": "Apache Commons IO",
  "commons-cli": "Apache Commons CLI",
  guava: "Guava",
  okhttp: "OkHttp",
  retrofit: "Retrofit",
  httpclient: "Apache HttpClient",
  gson: "Gson",
  "jackson-databind": "Jackson",
  "jackson-core": "Jackson",
  "jackson-annotations": "Jackson",
  json: "org.json",
  poi: "Apache POI",
  "poi-ooxml": "Apache POI",
  jsoup: "Jsoup",
  "jaxb-api": "JAXB API",
  "jaxb-runtime": "JAXB Runtime",
};

export const DOTNET_DEPS = {
  "Microsoft.AspNetCore.Mvc": "ASP.NET Core MVC",
  "Microsoft.EntityFrameworkCore": "Entity Framework Core",
  "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "ASP.NET Core Identity",
  "Microsoft.Extensions.Logging": "Logging",
  "Newtonsoft.Json": "Json.NET",
  AutoMapper: "AutoMapper",
  MediatR: "MediatR",
  FluentValidation: "FluentValidation",
  Serilog: "Serilog",
  NLog: "NLog",
  Dapper: "Dapper",
  Hangfire: "Hangfire",
  Quartz: "Quartz.NET",
  xunit: "xUnit.net",
  Moq: "Moq",
};

export const RUBY_DEPS = {
  rails: "Ruby on Rails",
  sinatra: "Sinatra",
  rspec: "RSpec",
  "rspec-rails": "RSpec",
  capybara: "Capybara",
  active_record: "Active Record",
  devise: "Devise",
  puma: "Puma",
  sidekiq: "Sidekiq",
  pg: "PostgreSQL (pg gem)",
  mysql2: "MySQL (mysql2 gem)",
};

export const PHP_DEPS = {
  "laravel/framework": "Laravel",
  "symfony/symfony": "Symfony",
  "symfony/http-kernel": "Symfony",
  "symfony/console": "Symfony",
  "symfony/framework-bundle": "Symfony",
  "codeigniter4/framework": "CodeIgniter",
  "yiisoft/yii2": "Yii",
  "phalcon/cphalcon": "Phalcon",
  "slim/slim": "Slim",
  "laminas/laminas-mvc": "Laminas (Zend)",
  "cakephp/cakephp": "CakePHP",
  "doctrine/orm": "Doctrine ORM",
  "monolog/monolog": "Monolog",
  "guzzlehttp/guzzle": "Guzzle",
  "phpunit/phpunit": "PHPUnit",
  "phpspec/phpspec": "PHPSpec",
  "vlucas/phpdotenv": "phpdotenv",
};

export const GO_DEPS = {
  "github.com/gin-gonic/gin": "Gin",
  "github.com/labstack/echo/v4": "Echo",
  "github.com/labstack/echo": "Echo",
  "github.com/gorilla/mux": "Gorilla Mux",
  "gorm.io/gorm": "GORM",
  "github.com/jmoiron/sqlx": "SQLX",
  "github.com/gofiber/fiber/v2": "Fiber",
  "github.com/go-chi/chi/v5": "Gochi",
  "github.com/revel/revel": "Revel",
  "github.com/gobuffalo/buffalo": "Buffalo",
  "github.com/stretchr/testify": "Testify",
  "github.com/sirupsen/logrus": "Logrus",
  "go.uber.org/zap": "Zap",
  "github.com/spf13/viper": "Viper",
  "github.com/spf13/cobra": "Cobra",
  "google.golang.org/grpc": "gRPC",
  "github.com/lib/pq": "PostgreSQL (lib/pq)",
  "github.com/go-sql-driver/mysql": "MySQL (go-sql-driver)",
};

export const RUST_DEPS = {
  actix: "Actix",
  "actix-web": "Actix Web",
  rocket: "Rocket",
  warp: "Warp",
  tokio: "Tokio",
  hyper: "Hyper",
  diesel: "Diesel",
  sqlx: "SQLX",
  serde: "Serde",
  serde_json: "Serde JSON",
  clap: "Clap",
  log: "Log",
  env_logger: "env_logger",
  reqwest: "Reqwest",
  rusqlite: "Rusqlite",
};

export const DART_DEPS = {
  flutter: "Flutter",
  dio: "Dio",
  http: "HTTP",
  provider: "Provider",
  riverpod: "Riverpod",
  flutter_riverpod: "Riverpod",
  hooks_riverpod: "Riverpod",
  bloc: "BLoC",
  flutter_bloc: "BLoC",
  sqflite: "Sqflite",
  shared_preferences: "Shared Preferences",
  json_serializable: "Json Serializable",
  get_it: "GetIt",
  freezed: "Freezed",
  freezed_annotation: "Freezed",
  go_router: "Go Router",
};

export const ELIXIR_DEPS = {
  phoenix: "Phoenix",
  ecto: "Ecto",
  ecto_sql: "Ecto SQL",
  plug: "Plug",
  plug_cowboy: "Plug Cowboy",
  absinthe: "Absinthe",
  poison: "Poison",
  jason: "Jason",
  ex_doc: "ExDoc",
  ex_unit: "ExUnit",
  gettext: "Gettext",
  credo: "Credo",
};

export const DOCKER_DEPS = {
  node: "Node.js (Docker)",
  python: "Python (Docker)",
  java: "Java (Docker)",
  openjdk: "Java (Docker)",
  amazoncorretto: "Java (Docker)",
  maven: "Maven (Docker)",
  gradle: "Gradle (Docker)",
  golang: "Go (Docker)",
  rust: "Rust (Docker)",
  ruby: "Ruby (Docker)",
  php: "PHP (Docker)",
  nginx: "Nginx (Docker)",
  httpd: "Apache HTTP Server (Docker)",
  postgres: "PostgreSQL (Docker)",
  mysql: "MySQL (Docker)",
  redis: "Redis (Docker)",
  mongo: "MongoDB (Docker)",
  alpine: "Alpine (Docker)",
  ubuntu: "Ubuntu (Docker)",
  debian: "Debian (Docker)",
  centos: "CentOS (Docker)",
};
